baseURL: https://docs.velociraptor.app/
languageCode: en-us
title: "Velociraptor - Digging deeper!"

theme: "hugo-theme-learn"
disqusShortname: velocidex-velociraptor
#security:
#  enableInlineShortcodes: true

params:
  noDisqus: true
  themeVariant: "mine"
  disableSearch: true
  showVisitedLinks: false
  disableMermaid: true
  disableBreadcrumb: true
  disableNextPrev: true
  disableLandingPageButton: true
  disableShortcutsTitle: true
  editURL: https://github.com/Velocidex/velociraptor-docs/edit/master/content/
  custom_css:
    - css/dark.css
    - css/syntax.css
    - css/light.css
    - css/hljs.css
    - https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    noClasses: false
    # Disable hugo syntax highlight because we use highlight.js
    codeFences: false

menu:
  shortcuts:
   -  name: "<i class='fab fa-github'></i>Github"
      identifier: "gh"
      url: "https://github.com/Velocidex/velociraptor"
      weight: 10
   -  name: "<i class='fab fa-discord'></i>Discord"
      identifier: "ds"
      url: "/discord/"
      weight: 20
   -  name: "<i class='fab fa-youtube'></i>YouTube"
      identifier: "yt"
      url: "/youtube/"
      weight: 25
   -  name: "<i class='fas fa-envelope'></i>Mailing List"
      identifier: "mail"
      url: "mailto:velociraptor-discuss@googlegroups.com"
      weight: 30
   -  name: "<i class='fas fa-rss'></i>RSS"
      identifier: "rss"
      url: "/rss/"
      weight: 40
   -  name: "<i class='fa fa-question-circle'></i>Rapid7 Docs"
      url: "https://docs.rapid7.com/"
      weight: 50

googleAnalytics: G-QYH72LMYCS

# We only want RSS to be generated in some areas.
outputs:
  page: ["HTML"]
  home: ["HTML"]
  section: ["HTML"]
  taxonomyTerm: ["HTML"]
  taxonomy: ["HTML"]
